### PR TITLE
added genre and director repo

### PR DESCRIPTION
**Pull request by Rubydoo17**

### CODE REVIEW

**Review by OEUG99 — CHANGES_REQUESTED** [review]
Can we get update() and getAll() for genre, these will be useful I believe.

**Review by OEUG99 — CHANGES_REQUESTED** [review]
This also could benefit from update() and getAll()

**Comment by Rubydoo17** [comment]
I think I already put in update() and getAll() functions in the genre repo. Are they not visible? They look like this: 
def update(self, obj):
        """
        Updates a genre in the database, returns the updated Genre object
        :param obj:
        :type obj:
        :return:
        :rtype:
        """
        pass

def getAll(self):
        """
        Gets all genres from the database
        :return:
        :rtype:
        """
        pass

**Comment by OEUG99** [comment]
Yes, you have their protypes/placeholder code but we need them written out to communicate with the database. The `pass` in python is just a placeholder.

**Comment by OEUG99** [comment]
A good example for Update() can be [found here](https://github.com/OEUG99/ReelLoveDating-Monolithic/blob/master/backend/src/repositories/ProfileRepository.py)

**Pull request closed without merging**
